// <auto-generated />
using Data.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Data.Core.Models.TelegramBotParams", b =>
                {
                    b.Property<int>("TelegramBotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AcceptElectronicReceipts")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AcceptPromotionsBySms")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("BotName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BotUserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HelloText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Menu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TokenApi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TosUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WebHookUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TelegramBotId");

                    b.ToTable("TelegramParams");
                });
#pragma warning restore 612, 618
        }
    }
}
